apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 361425201728.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 361425201728.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: latest
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
